flipper:
    ID: 1
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0

    ID: 2
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0

    ID: 3
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0

    ID: 4
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0
